// var nodemailer = require('nodemailer');
//
// const dotenv = require('dotenv')
// dotenv.config()
//
// const username = process.env.USERRNAME
// const password = process.env.PASSWORD
//
// // transporter.verify(function(error, success) {
// //    if (error) {
// //         console.log(error);
// //    } else {
// //         console.log('Server is ready to take our messages');
// //    }
// // });
//
// exports.sendMail = nodemailer.createTransport({
//     host: "smtp.mailtrap.io",
//     port: 2525,
//     auth: {
//         user: username, //generated by Mailtrap
//         pass: password //generated by Mailtrap
//     }
// });
//
// var mailOptions = {
//   from: 'Enyata Team',
//   to: useremail,
//   subject: subject,
//   text: text
// };
//
// transporter.sendMail(mailOptions, function(error, info){
//   if (error) {
//
//   } else {
//     console.log('Email sent: ' + info.response);
//   }
// });
